# Generated by Django 3.0.5 on 2020-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmu',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
