# Generated by Django 3.0.5 on 2020-05-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hong', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hong',
            new_name='HongdaeBoardModel',
        ),
    ]
