# Generated by Django 3.0.5 on 2020-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hong', '0002_auto_20200528_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hongdaeboardmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
