# Generated by Django 3.0.5 on 2020-06-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hong', '0003_auto_20200528_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='HongdaeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hong.HongdaeBoardModel')),
            ],
        ),
    ]
