# Generated by Django 3.0.5 on 2020-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockdong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockdongboard',
            old_name='tutle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='mockdongboard',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
